#workflow name
name: "simple workflow pm2 configuration"

#event, trigger action that running our Jobs.
#In this file we trigger pm2-configuration every we push code to repository.
on: [push]
jobs:
  pm2-configuration:
    #runner, This job will be running in runner with Ubuntu Server latest version.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #checkout code from repository, so we code downloaded in runner.
      - uses: actions/setup-node@v3 #setup nodejs in our runner
      #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      - run: pm2 start index.js --watch -i max
